# Pipeline to auto review a pull request with claude code
name: Claude Code Review
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

permissions:
  id-token: write
  contents: read
  pull-requests: write # permissions for claude to comment on the pull request
  issues: write # permissions for claude to comment on the pull request


jobs:
  claude-review:
    uses: uptick/actions/.github/workflows/claude_review.yaml@main
    secrets: inherit