# Pipeline to invoke claude code on @claude in comments, issues, pull requests, etc.
name: Claude Code Mention
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

permissions:
  id-token: write
  contents: read
  pull-requests: write # permissions for claude to comment on the pull request
  issues: write # permissions for claude to comment on the pull request
  actions: read # Required for Claude to read CI results on PRs


jobs:
  claude-mention:
    uses: uptick/actions/.github/workflows/claude_mention.yaml@main
    secrets: inherit