# Pipeline to auto review a pull request with claude code
name: Claude Code Review
on:
  pull_request:
    types: [opened, synchronize]

permissions:
  id-token: write
  contents: read
  pull-requests: write # permissions for claude to comment on the pull request
  issues: write # permissions for claude to comment on the pull request

jobs:
  claude-review:
    uses: uptick/actions/.github/workflows/claude_review.yaml@main # ratchet:exclude
    secrets: inherit
