name: Lint
on:
  pull_request: {}

permissions:
  id-token: write # Required for federated aws oidc
  actions: read
  contents: read
  pull-requests: write

jobs:
  lint:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit
    with:
      command: |
        mise run install
        mise run lint
      mise: true
      mise-install: true
