name: Test Python
on:
  pull_request: {}

permissions:
  id-token: write # Required for federated aws oidc
  actions: read
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests


jobs:
  python-command:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit
    with:
      command: echo good
      debug: true
      poetry: true
      poetry-install: true
      poetry-install-command: "poetry install --all-extras"