name: Test uv installation
on:
  pull_request: {}
  push:
    branches:
      - main

permissions:
  id-token: write # Required for federated aws oidc
  actions: read
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests

jobs:
  test-bump-app:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit
    with:
      debug: true
      bump-app: "tickforge"
      command: |
        echo "test"
