name: Test Slack Error
on:
  pull_request: {}

permissions:
  id-token: write # Required for federated aws oidc
  contents: read
  actions: read
  pull-requests: write

jobs:
  slack-error:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit
    with:
      command: echo good
      debug: true
      slack-channel: devops-test-slack