name: Test Checkout
on:
  pull_request: {}

permissions:
  id-token: write # Required for federated aws oidc
  contents: read
  actions: read
  pull-requests: write

jobs:
  checkout-ref:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit
    with:
      checkout-ref: "main"
      command: echo good
      debug: true
