name: Test Docker
on:
  pull_request: {}
  push:
    branches:
      - main

permissions:
  id-token: write # Required for federated aws oidc
  actions: read
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests

jobs:
  docker-prefix-specified:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit
    with:
      command: echo good
      debug: true
      docker-enabled: true
      docker-prefix: main
      docker-tag-latest: true
      docker-tag: testlol
      docker-repository: 610829907584.dkr.ecr.ap-southeast-2.amazonaws.com/github-actions-ci

  docker-no-prefix-specified:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit
    with:
      command: echo good
      debug: true
      docker-enabled: true
      docker-repository: 610829907584.dkr.ecr.ap-southeast-2.amazonaws.com/github-actions-ci
